### ISSUE TITLE
Oscillating NACA0012 in LusgsFoam

### ISSUE THREAD

**Issue by tiandixuanhuang1** [furstj/myFoam#18]
Dear Professor Jiri Furst:

My name is Wu Lei, and I am a master student from Xi'an Jiaotong University.Recently, I saw the LU-SGS method you implanted on Github, then I read your paper ”Development of a coupled matrix-free LU-SGS solver for turbulent compressible flows” and I found it great and attractive. I have benefited a lot from learning your codes.

I am very interested in the example NACA0012 in your paper, I am emailing to you for asking if you could share this case with me, I recently want to test different schemes to calculate this case. And I will introduce your solver in my first article.

Thanks!

my email: leiwu2201@qq.com

Yours sincerely

**Comment by furstj** [comment]
Hi,

I just added the oscillating NACA 0012 into tutorials of myFoam repository. The mesh is relatively coarse and the flow is inviscid. 

best regards,

Jiri

**Comment by tiandixuanhuang1** [comment]
Thanks for professor's reply!  : )
