### ISSUE TITLE
How to extend myFoam to MRF case?

### ISSUE THREAD

**Issue by jiaqiwang969** [furstj/myFoam#8]
Hi furstj.
      I found that the solver works in the MRF case, could you provide a basic cases? So far I know that for example in "https://www.youtube.com/watch?v=eDUXXcXfX44", public openfoam only offers MRF for incompressible flows (simpleFoam).
      My question is how to extend rhopimpleFoam or your solver to Dynamic mesh or MRF?
Thanks~

**Comment by furstj** [comment]
Hi, my solver works both with MRF or dynamic mesh. If you are interested in, I will add a simple tutorial case tomorrow or during the weekend.

**Comment by furstj** [comment]
@jiaqiwang969 I've just added two tutorial cases. One for MRF, second one for dynamic mesh. See tutorials/myLusgsFoam/ercoftacCentrifugalPump_*

Note that both cases correspond to https://www.openfoamwiki.net/index.php/Sig_Turbomachinery_/_ERCOFTAC_centrifugal_pump_with_a_vaned_diffuser 
which is originally for incompressible flows. MyLusgsFoam is not very efficient for this case. pimpleFoam would be better here :).
